import type { Metadata } from "next";
import { Playfair_Display, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./_components/partials/Header";
import Footer from "./_components/partials/Footer";
import BookingFloating from "./_components/BookingFloating";
import CTWAFloating from "./_components/CTWAFloating";
import ScrollToTop from "./_components/ScrollToTop";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${montserrat.variable} antialiased font-monsterrat`}
      >
        <Header />
        <ScrollToTop />

        <main className="w-full overflow-hidden">{children}</main>
        <BookingFloating />
        <CTWAFloating />
        <Footer />
      </body>
    </html>
  );
}
